--- #YAML:1.0
name:               Drupal-Admin
version:            .01
abstract:           screen scraping Perl API to some Drupal admin functions
author:
    - Dan Urist <durist@frii.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Type:           0
    Getopt::Long:         0
    Log::Log4perl:        0
    Moose:                0
    MooseX::Log::Log4perl::Easy:  0
    Pod::Usage:           0
    Test::More:           0
    WWW::Mechanize:       0
    WWW::Mechanize::TreeBuilder:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
