--- #YAML:1.0
name:                Drupal-Admin
version:             0.03
abstract:            screen scraping Perl API to some Drupal admin functions
license:             perl
author:              
    - Dan Urist <durist@frii.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Type:                    0
    Getopt::Long:                  0
    Log::Log4perl:                 0
    Moose:                         0
    MooseX::Log::Log4perl::Easy:   0
    Pod::Usage:                    0
    Test::More:                    0
    WWW::Mechanize:                0
    WWW::Mechanize::TreeBuilder:   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
